[phases.setup]
nixPkgs = ['nodejs_20']

[phases.build]
cmds = ['cd server && npm install --include=dev && npm run build']

[phases.start]
cmd = 'cd server && npm start'

[variables]
NODE_ENV = 'production'
