[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']

[phases.build]
cmds = ['cd server && npm install && npm run build']

[phases.start]
cmd = 'cd server && npm start'

[variables]
NODE_ENV = 'production'
